USE [master]
GO

/****** Object:  Database [DaveValeyVinyard]    Script Date: 11/7/2018 3:57:00 PM ******/
CREATE DATABASE [DaveValeyVinyard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DaveValeyVinyard', FILENAME = N'C:\mount\SQLDATA1\MSSQL\MSSQL13.CIS355\MSSQL\DATA\DaveValeyVinyard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DaveValeyVinyard_log', FILENAME = N'C:\Mount\SQLLogs1\MSSQL\MSSQL13.CIS355\MSSQL\Data\DaveValeyVinyard_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DaveValeyVinyard] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DaveValeyVinyard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DaveValeyVinyard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET ARITHABORT OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DaveValeyVinyard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DaveValeyVinyard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DaveValeyVinyard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DaveValeyVinyard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DaveValeyVinyard] SET  MULTI_USER 
GO

ALTER DATABASE [DaveValeyVinyard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DaveValeyVinyard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DaveValeyVinyard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DaveValeyVinyard] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DaveValeyVinyard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DaveValeyVinyard] SET QUERY_STORE = OFF
GO

USE [DaveValeyVinyard]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DaveValeyVinyard] SET  READ_WRITE 
GO

