--Deletes the database and recreate it with the most up to date tables
USE master DROP DATABASE IF EXISTS ValleyVinyardsDaveIanTanner;
CREATE DATABASE ValleyVinyardsDaveIanTanner;
USE ValleyVinyardsDaveIanTanner

--Creates Tables in the new version of the Database
CREATE TABLE PeopleAndCustomers (
	PCID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FullName VARCHAR(80),
	Phone INT,
	StreetAddress VARCHAR(100),
	Email VARCHAR(80),
	PersonType CHAR
);

CREATE TABLE Employee (
	EID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EmployeeType CHAR,
	EmergencyContact INT,
	PCID INT FOREIGN KEY REFERENCES PeopleAndCustomers(PCID),
	Manager INT FOREIGN KEY REFERENCES Employee(EID), 
	SSN INT
);

CREATE TABLE PlotOfLand (
	LID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EID INT NOT NULL FOREIGN KEY REFERENCES Employee(EID),
	PlotName VARCHAR(40),
	Size VARCHAR(40),
	OwnedBy INT FOREIGN KEY REFERENCES Employee(EID),
);

CREATE TABLE GrapeVariety (
	GID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VarietyName VARCHAR(40),
	GrapeToJuiceRatio DECIMAL,
	StorageProperties NVARCHAR(40),
	WineAgingRequirements NVARCHAR(40) 
);

CREATE TABLE HarvestedPlot (
	HPID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GID INT NOT NULL FOREIGN KEY REFERENCES GrapeVariety(GID),
	LID INT NOT NULL FOREIGN KEY REFERENCES PlotOfLand(LID),
	WeightTotal INT,
);

CREATE TABLE GrapeContainer (
	GCID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	HPID INT NOT NULL FOREIGN KEY REFERENCES HarvestedPlot(HPID),
	StorageType VARCHAR(40),
	StorageSize VARCHAR(40),
	DateStored DATETIME,
	LocationName VARCHAR(40),
	TotalWeight INT,
	LocationID INT
);

CREATE TABLE Certification (
	CertID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DescriptionOf NVARCHAR(200),
);

CREATE TABLE EmployeeCertification (
	CertID INT NOT NULL REFERENCES Certification(CertID),
	EID INT NOT NULL REFERENCES Employee(EID),
	CertifiedOn Date,
	DidPass BIT,
	PRIMARY KEY (CertID, EID)
);

CREATE TABLE JobTitle (
	JID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	JobDescription NVARCHAR(200),
	Position NVARCHAR(40)
);

CREATE TABLE EmployeeJob (
	EID INT NOT NULL REFERENCES Employee(EID),
	JID INT NOT NULL REFERENCES JobTitle(JID),
	Pay SMALLMONEY,
	StartDate DATE NOT NULL,
	EndDate DATE,
	PRIMARY KEY (JID, EID)
);

CREATE TABLE Vendor (
	VID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PCID INT FOREIGN KEY REFERENCES PeopleAndCustomers(PCID),
	PrimaryContactPhone INT,
	PrimaryContactName NVARCHAR(40),
	VendorDescription NVARCHAR(200),
);

CREATE TABLE WineBottleOrder (
	WBOID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VID INT FOREIGN KEY REFERENCES Vendor(VID),
	OrderedOn DATE,
	ReceivedOn DATE
);

CREATE TABLE WineBottleType (
	WBTID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MSRP SMALLMONEY,
	Size INT,
	Shape NVARCHAR(25),
	Color NVARCHAR(25),
	Inventory INT
);

CREATE TABLE WineBottleOrderLine (
	WBOID INT NOT NULL REFERENCES WineBottleOrder(WBOID),
	WBTID INT NOT NULL REFERENCES WineBottleType(WBTID),
	Quantity INT,
	SalePrice SMALLMONEY,
	PRIMARY KEY(WBOID, WBTID)
);

CREATE TABLE IndividualCustomer (
	CID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PCID INT NOT NULL FOREIGN KEY REFERENCES PeopleAndCustomers(PCID),
	DateOfBirth Date,
	Preferences NVARCHAR(50)
);

CREATE TABLE BusinessCustomer (
	BCID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PCID INT NOT NULL FOREIGN KEY REFERENCES PeopleAndCustomers(PCID),
	TaxIDNumber INT,
	ResaleLicenseNumber INT,
	Discount INT,
	Preferences NVARCHAR(50)
);

CREATE TABLE CustomerOrder (
	COID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PCID INT NOT NULL FOREIGN KEY REFERENCES PeopleAndCustomers(PCID),
	OrderedOn DATETIME,
	OrderStatus NVARCHAR(20)
);

CREATE TABLE CustomerOrderLine (
	COLID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COID INT NOT NULL FOREIGN KEY REFERENCES CustomerOrder(COID),
	Quantity INT,
	PricePaid SMALLMONEY
);

CREATE TABLE CaseLots (
	WBTID INT NOT NULL REFERENCES WineBottleType(WBTID),
	COLID INT NOT NULL REFERENCES CustomerOrderLine(COLID),
	BottlesPerCase INT,
	BoxDimension VARCHAR(20),
	Price SMALLMONEY,
	PRIMARY KEY(WBTID, COLID)
);

CREATE TABLE WineBatch (
	WID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	StorageDate DATETIME,
	BottlingDate DATETIME,
	Volume FLOAT,
	WBTID INT NOT NULL FOREIGN KEY REFERENCES WineBottleType(WBTID),
	Category VARCHAR(40),
	PercentAlcohol FLOAT,
	EID INT NOT NULL FOREIGN KEY REFERENCES Employee(EID)
);

CREATE TABLE WineStorage (
	WSID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	WID INT NOT NULL FOREIGN KEY REFERENCES WineBatch(WID),
	SizePerUnit INT,
	MaterialType VARCHAR(40),
	LocationID INT,
	Quantity INT
);

CREATE TABLE ProductionOrder (
	POID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
);

CREATE TABLE GrapeFermentation (
	GFID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	WID INT NOT NULL FOREIGN KEY REFERENCES WineBatch(WID),
	POID INT NOT NULL FOREIGN KEY REFERENCES ProductionOrder(POID),
	StartDate DATETIME,
	EndDate DATETIME,
	FermentationType VARCHAR(40)
);

CREATE TABLE Recipe (
	RID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	WineName VARCHAR(60),
	CreatedOn DATE,
	PrimaryGrape INT FOREIGN KEY REFERENCES GrapeVariety(GID),
	Yeast VARCHAR(60),
	Category VARCHAR(60)
);

CREATE TABLE ProductionOrderLine (
	POLID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RID INT FOREIGN KEY REFERENCES Recipe(RID),
	GCID INT FOREIGN KEY REFERENCES GrapeContainer(GCID),
	POID INT FOREIGN KEY REFERENCES ProductionOrder(POID),
	DateRequested DateTime
);

CREATE TABLE UsedInRecipe (
	GCID INT NOT NULL REFERENCES GrapeContainer(GCID),
	RID INT NOT NULL REFERENCES Recipe(RID),
	GrapeRatio DECIMAL,
	PRIMARY KEY(GCID, RID)
);
